### ISSUE TITLE
How to use this package in JavaScript but not TypeScript?

### ISSUE THREAD

**Issue by kwhsiung** [kevinptt0323/ptt-client#13]
I'm trying to use this great package in Node v10, in JavaScript but not TypeScript.

However, it seems the process just exit without any stdout or stderr.

Here is my reproduce: https://repl.it/repls/FlawedMiserlyKeygen, the `Promise { <pending> }` stdout is only show on Repl.it platform, if you reproduce this JavaScript file in local Node environment like `node index.js`, process just exit immediately without any stdout or stderr too.

**Comment by kevinptt0323** [comment]
We fixed this issue in 1783ca4, but I forgot to released it XD. I'll release ASAP.

You can temporarily fix it by using:

```js
const ptt = new Ptt.default({origin: 'app://your-app-name'});
```

Thanks!

**Comment by kevinptt0323** [comment]
BTW, I strongly recommend you to use ES8 `async`/`await` instead of `Promise` because we will have more and more asynchronous operations future. As far as I know, you can use [async function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/async_function) since Node.js 7.6.0.

**Comment by kwhsiung** [comment]
The origin workaround works, thanks for replying 😄
